# Generated by Django 4.0.4 on 2022-05-30 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite', models.BooleanField(default=False, verbose_name='Избранная')),
                ('rating', models.CharField(blank=True, choices=[('1', 'terribly'), ('2', 'bad'), ('3', 'ok'), ('4', 'good'), ('5', 'amazing')], max_length=25, null=True, verbose_name='Рейтинг фильма')),
                ('in_plans', models.BooleanField(default=False, verbose_name='В планах')),
                ('viewed', models.BooleanField(default=False, verbose_name='Просмотренно ранее')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='film.film', verbose_name='Фильм')),
            ],
            options={
                'verbose_name': 'Фильм в библиотеки',
                'verbose_name_plural': 'Фильмы библиотеки ',
            },
        ),
        migrations.CreateModel(
            name='UserLibrary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('films', models.ManyToManyField(blank=True, related_name='Фильм', to='userlibrary.userfilm', verbose_name='Фильм')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец библиотеки')),
            ],
            options={
                'verbose_name': 'Библиотка пользователя',
                'verbose_name_plural': 'Библиотеки пользователей',
            },
        ),
        migrations.AddField(
            model_name='userfilm',
            name='library',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Библиотека', to='userlibrary.userlibrary', verbose_name='Библиотека'),
        ),
        migrations.AddField(
            model_name='userfilm',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Владелец библиотеки'),
        ),
    ]
