// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AuthDialog: typeof import('./src/components/dialogs/AuthDialog.vue')['default']
    AuthDialogForm: typeof import('./src/components/forms/AuthDialogForm.vue')['default']
    CommonHeader: typeof import('./src/components/CommonHeader.vue')['default']
    CommonRecommend: typeof import('./src/components/CommonRecommend.vue')['default']
    CommonSwiper: typeof import('./src/components/CommonSwiper.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    HeroSlider: typeof import('./src/components/HeroSlider.vue')['default']
    HeroSwiper: typeof import('./src/components/HeroSwiper.vue')['default']
    MainHero: typeof import('./src/components/MainHero.vue')['default']
    MainMovie: typeof import('./src/components/MainMovie.vue')['default']
    MostPopular: typeof import('./src/components/MostPopular.vue')['default']
    RegDialogForm: typeof import('./src/components/forms/RegDialogForm.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
