version: '3.8'

services:
  web:
    container_name: rust-anime-summer
    build:
      context: ./
      dockerfile: Dockerfile
    env_file: .env
    ports:
      - "${APP_PORT}:${APP_PORT}"
    volumes:
      - ./:/opt/rust-anime-summer/
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    container_name: rust-todo-db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file: .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 10s
      timeout: 15s
      retries: 5


volumes:
  postgres_data:
