# Generated by Django 4.0.4 on 2022-05-30 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=75)),
                ('message', models.TextField(max_length=1024)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='')),
            ],
            options={
                'verbose_name': 'Писмо от пользователя',
                'verbose_name_plural': 'Письма от пользвателей',
            },
        ),
        migrations.CreateModel(
            name='MailingLetters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=75)),
                ('message', models.TextField(max_length=1024)),
                ('attachments', models.FileField(blank=True, null=True, upload_to='')),
                ('is_send', models.CharField(choices=[('SEND', 'Отправить'), ('Draft', 'Черновик')], max_length=255)),
            ],
            options={
                'verbose_name': 'Писмь админа',
                'verbose_name_plural': 'Письма админа',
            },
        ),
    ]
