# Generated by Django 4.0.4 on 2022-05-11 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='composer',
            field=models.ManyToManyField(blank=True, related_name='composer', to='film.people', verbose_name='Композитор фильма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='director',
            field=models.ManyToManyField(blank=True, related_name='director', to='film.people', verbose_name='Режисер фильма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='mounting',
            field=models.ManyToManyField(blank=True, related_name='mounting', to='film.people', verbose_name='Монтажер фильма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='operator',
            field=models.ManyToManyField(blank=True, related_name='operator', to='film.people', verbose_name='Оператор фильма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='producer',
            field=models.ManyToManyField(blank=True, related_name='producer', to='film.people', verbose_name='Продюсер фильма'),
        ),
        migrations.AlterField(
            model_name='film',
            name='starring',
            field=models.ManyToManyField(blank=True, related_name='starring', to='film.people', verbose_name='Главные актеры'),
        ),
    ]
