# Generated by Django 4.0.4 on 2022-05-14 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='year',
        ),
    ]
