# Generated by Django 4.0.4 on 2022-05-14 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_remove_film_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.PositiveIntegerField(default=0, verbose_name='Год выпуска фильма'),
            preserve_default=False,
        ),
    ]
