# Generated by Django 4.0.4 on 2022-05-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0002_alter_film_composer_alter_film_director_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='film',
            name='genre',
            field=models.ManyToManyField(blank=True, to='film.genre', verbose_name='Жанры фильма'),
        ),
    ]
