# Generated by Django 4.0.4 on 2022-05-14 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0003_film_year'),
    ]

    operations = [
        migrations.RenameField(
            model_name='film',
            old_name='covet_mini',
            new_name='cover_mini',
        ),
    ]
