# Generated by Django 4.0.4 on 2022-05-14 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('film', '0004_rename_covet_mini_film_cover_mini'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='composer',
        ),
        migrations.RemoveField(
            model_name='film',
            name='director',
        ),
        migrations.RemoveField(
            model_name='film',
            name='mounting',
        ),
        migrations.RemoveField(
            model_name='film',
            name='operator',
        ),
        migrations.RemoveField(
            model_name='film',
            name='producer',
        ),
        migrations.RemoveField(
            model_name='people',
            name='profession',
        ),
    ]
