# Generated by Django 4.0.4 on 2022-05-16 09:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('film', '0005_remove_film_composer_remove_film_director_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField(max_length=1024, verbose_name='Тело текста')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания комментария')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время последнего обновления комментария')),
                ('active', models.BooleanField(default=True, verbose_name='Состояние комментария')),
                ('rating', models.CharField(blank=True, choices=[('1', 'terribly'), ('2', 'bad'), ('3', 'ok'), ('4', 'good'), ('5', 'amazing')], max_length=25, null=True, verbose_name='Рейтинг фильма')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='film.film', verbose_name='Комменитрованный фильм')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='film.comment', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
            },
        ),
    ]
